force-app/main/default/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <label>Donation</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Donation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donation__c/fields/Associated_Fundraising_Action__c.field-meta.xml
<CustomField>
    <fullName>Associated_Fundraising_Action__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Associated Fundraising Action</label>
    <referenceTo>Fundraising_Action__c</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Donor_Name__c.field-meta.xml
<CustomField>
    <fullName>Donor_Name__c</fullName>
    <label>Donor Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/Fundraising_Action__c.object-meta.xml
<CustomObject>
    <label>Fundraising Action</label>
    <nameField>
        <displayFormat>FA-{000000}</displayFormat>
        <label>Fundraising Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fundraising Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fundraising_Action__c/fields/Amount_Raised__c.field-meta.xml
<CustomField>
    <fullName>Amount_Raised__c</fullName>
    <label>Amount Raised</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Associated_Military_Request__c.field-meta.xml
<CustomField>
    <fullName>Associated_Military_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Associated Military Request</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Military_Request__c.Visibility__c</field>
            <operation>equals</operation>
            <value>Visible to Volunteers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Military_Request__c</referenceTo>
    <relationshipLabel>Fundraising Actions</relationshipLabel>
    <relationshipName>Fundraising_Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Fundraising_Goal__c.field-meta.xml
<CustomField>
    <fullName>Fundraising_Goal__c</fullName>
    <label>Fundraising Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Military_Request__c/Military_Request__c.object-meta.xml
<CustomObject>
    <label>Military Request</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Military Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Military Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Military_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Fundraising</fullName>
            </value>
            <value>
                <fullName>Fundraising Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DonationHandler.cls
public with sharing class DonationHandler {

    public static void createDonate(String donorFullName, String fundraisingId, Decimal amount){
        Donation__c newDonate = new Donation__c();
        newDonate.Donor_Name__c = donorFullName;
        newDonate.Associated_Fundraising_Action__c = fundraisingId;
        newDonate.Amount__c = amount;
        insert newDonate;

        Fundraising_Action__c fa = [SELECT Amount_Raised__c, Associated_Military_Request__c, Fundraising_Goal__c, Status__c FROM Fundraising_Action__c WHERE Id=:fundraisingId LIMIT 1];
        Decimal faAmountReached = fa.Amount_Raised__c + amount;
        if (faAmountReached >= fa.Fundraising_Goal__c) {
            fa.Status__c = 'Completed';
            Military_Request__c mr = [SELECT Status__c FROM Military_Request__c WHERE Id =: fa.Associated_Military_Request__c LIMIT 1];
            mr.Status__c = 'Fundraising Complete';
            update mr;
        }
        fa.Amount_Raised__c = faAmountReached;

        update fa;
    }

}