force-app/main/default/objects/Fundraising_Action__c/Fundraising_Action__c.object-meta.xml
<CustomObject>
    <label>Fundraising Action</label>
    <nameField>
        <displayFormat>FA-{000000}</displayFormat>
        <label>Fundraising Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fundraising Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fundraising_Action__c/fields/Amount_Raised__c.field-meta.xml
<CustomField>
    <fullName>Amount_Raised__c</fullName>
    <label>Amount Raised</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Associated_Military_Request__c.field-meta.xml
<CustomField>
    <fullName>Associated_Military_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Associated Military Request</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Military_Request__c.Visibility__c</field>
            <operation>equals</operation>
            <value>Visible to Volunteers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Military_Request__c</referenceTo>
    <relationshipLabel>Fundraising Actions</relationshipLabel>
    <relationshipName>Fundraising_Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Fundraising_Goal__c.field-meta.xml
<CustomField>
    <fullName>Fundraising_Goal__c</fullName>
    <label>Fundraising Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fundraising_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Military_Request__c/Military_Request__c.object-meta.xml
<CustomObject>
    <label>Military Request</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Military Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Military Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Military_Request__c/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <label>Requested Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Military_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Fundraising</fullName>
            </value>
            <value>
                <fullName>Fundraising Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Military_Request__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <label>Visibility</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Visible to Volunteers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StripePaymentControllerTest.cls
@isTest
public class StripePaymentControllerTest {
    
    @IsTest
    static void testHandleRedirectSuccess() {
        User volunteerUser = new User(
            Username = 'testuser@domain.com',
            LastName='testuser',
            Email = 'testuser@domain.com',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id, // Ensure a valid ProfileId is set
            Alias = 'testuser',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            CommunityNickname = 'testvolunteer'
        );
    insert volunteerUser;
    
    Military_Request__c mr = new Military_Request__c();
    mr.Requested_Amount__c = 20000;
    mr.Status__c = 'New';
    mr.Visibility__c = 'Visible to Volunteers';

    insert mr;
    
    Fundraising_Action__c fundraisingAction = new Fundraising_Action__c(
        Amount_Raised__c = 5000.00,
        Fundraising_Goal__c = 10000.00,
        Status__c = 'In Progress',
        Associated_Military_Request__c = mr.Id,
        Volunteer__c = volunteerUser.Id
    );
    insert fundraisingAction;
    StripePaymentMock mock = new StripePaymentMock();
    mock.setFundraisingId(fundraisingAction.Id);
        Test.setMock(HttpCalloutMock.class, mock);

        ApexPages.currentPage().getParameters().put('payment_intent', 'pi_12345');

        Test.startTest();
        PageReference result = new StripePaymentController().handleRedirect();
        Test.stopTest();

        System.assert(result.getUrl().contains('/apex/PaymentSuccessful'), 'The URL should redirect to the success page.');
        System.assert(result.getUrl().contains('transactionId=txn_123'), 'The transaction ID should match the mock response.');
    }

    @IsTest
    static void testHandleRedirectFailure() {
        MockHttpResponseGenerator mock = new MockHttpResponseGenerator();
        mock.setMockResponse(200, '{"data": [{"id": "txn_123", "status": "failed", "amount": 5000, "created": 1693276800, "currency": "uah", "metadata": {"donorEmail": "test@example.com", "donorFullName": "John Doe", "fundraisingId": "01IWV000000Ra93", "fundraisingName": "Charity Event"}, "payment_method_details": {"type": "card"}}]}');
        Test.setMock(HttpCalloutMock.class, mock);

        ApexPages.currentPage().getParameters().put('payment_intent', 'pi_12345');

        Test.startTest();
        PageReference result = new StripePaymentController().handleRedirect();
        Test.stopTest();

        System.assert(result.getUrl().contains('/apex/PaymentFailedPage'), 'The URL should redirect to the failure page.');
        System.assert(result.getUrl().contains('transactionId=txn_123'), 'The transaction ID should match the mock response.');
    }

    @isTest
    static void testGetCurrencySignByIsoCode() {
        StripePaymentController controller = new StripePaymentController();
        
        String usdSign = controller.getCurrencySignByIsoCode('usd');
        System.assertEquals('$', usdSign);
        
        String uahSign = controller.getCurrencySignByIsoCode('uah');
        System.assertEquals('₴', uahSign);
        
        String eurSign = controller.getCurrencySignByIsoCode('eur');
        System.assertEquals('€', eurSign);
        
        String gbpSign = controller.getCurrencySignByIsoCode('gbp');
        System.assertEquals('£', gbpSign);
        
        String unknownSign = controller.getCurrencySignByIsoCode('inr');
        System.assertEquals('', unknownSign); 
    }
   
}