force-app/main/default/objects/Fundraising_Action__c/Fundraising_Action__c.object-meta.xml
<CustomObject>
    <label>Fundraising Action</label>
    <nameField>
        <displayFormat>FA-{000000}</displayFormat>
        <label>Fundraising Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fundraising Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fundraising_Action__c/fields/Amount_Raised__c.field-meta.xml
<CustomField>
    <fullName>Amount_Raised__c</fullName>
    <label>Amount Raised</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Associated_Military_Request__c.field-meta.xml
<CustomField>
    <fullName>Associated_Military_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Associated Military Request</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Military_Request__c.Visibility__c</field>
            <operation>equals</operation>
            <value>Visible to Volunteers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Military_Request__c</referenceTo>
    <relationshipLabel>Fundraising Actions</relationshipLabel>
    <relationshipName>Fundraising_Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Fundraising_Goal__c.field-meta.xml
<CustomField>
    <fullName>Fundraising_Goal__c</fullName>
    <label>Fundraising Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fundraising_Action__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fundraising_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Military_Request__c/Military_Request__c.object-meta.xml
<CustomObject>
    <label>Military Request</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Military Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Military Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Military_Request__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supplies</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Military_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Fundraising</fullName>
            </value>
            <value>
                <fullName>Fundraising Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FundraisingActionController.cls
public with sharing class FundraisingActionController {
    @AuraEnabled
    public static List<Fundraising_Action__c> getFundraisingActionsByStatus(String status){
        try {
            return [SELECT Id, Name, Amount_Raised__c, Associated_Military_Request__r.Description__c, Associated_Military_Request__r.Category__c, Fundraising_Goal__c, Volunteer__r.Username FROM Fundraising_Action__c WHERE Status__c=:status];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}